# Generated by Django 6.0.6 on 2026-07-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_user_must_change_password_alter_post_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_content',
            field=models.FileField(blank=True, null=True, upload_to='video_content/'),
        ),
    ]
