# Generated by Django 6.0.6 on 2026-07-12 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_post_options_alter_post_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
